"""stealth_vps.wireguard — WireGuard config + key + IP-allocation helpers (v0.11.0+).

WireGuard is the "boring VPN fallback" for hard-DPI networks where every
probe-resistant transport gets killed simultaneously but plain WG UDP
passes (treated as a corporate VPN). Unlike the Xray-family protocols,
WG has no URI scheme — a client imports a multi-line `.conf` snippet.

This module is the pure, testable core:

  - generate_keypair()   — shell out to `wg genkey | wg pubkey`
  - allocate_client_ip() — next-free /32 in the configured /24
  - render_server_conf() — the server's wg-stealth.conf (Interface + N Peers)
  - render_client_conf() — one user's importable .conf (Interface + 1 Peer)

The Ansible side (tasks/wireguard.yml) calls generate_keypair for the
server + each new user, persists the server config, and `wg syncconf`s
to hot-reload without dropping live tunnels. The bot/CLI call
render_client_conf to hand a user their config.

Stdlib only — `ipaddress` for subnet math, `subprocess` for `wg`
(wireguard-tools, apt-installed by the role). No cryptography dep:
WG keys are generated by the canonical `wg` binary, not re-implemented.

Per the design doc's ADRs:
  - B2: subnet defaults to 10.99.0.0/24, operator-overridable.
  - B3: client IPs allocated sequentially (next-free), .1 reserved for
        the server interface.
  - B4: server-side keygen by default; the operator can supply a
        client-generated pubkey to skip the server minting a privkey.
"""

from __future__ import annotations

import ipaddress
import subprocess
from typing import Iterable

DEFAULT_WG_BIN = "wg"
DEFAULT_SUBNET = "10.99.0.0/24"
# DNS handed to clients in the generated .conf. Cloudflare's 1.1.1.1 is
# the default — operators wanting a different resolver override at the
# render_client_conf call site.
DEFAULT_CLIENT_DNS = "1.1.1.1"
# AllowedIPs in the client's [Peer] block — full-tunnel by default
# (route everything through the VPN). Split-tunnel operators override.
DEFAULT_CLIENT_ALLOWED_IPS = "0.0.0.0/0, ::/0"
# PersistentKeepalive (seconds) keeps the NAT mapping alive so the
# server can reach roaming clients. 25 is the WG community standard.
DEFAULT_KEEPALIVE = 25


class WireGuardError(Exception):
    """All WireGuard helper failures (keygen exec, subnet math, IP
    exhaustion) raise this for callers to catch uniformly."""


# ---------------------------------------------------------------------------
# Keypair generation
# ---------------------------------------------------------------------------


def generate_keypair(*, wg_bin: str = DEFAULT_WG_BIN) -> tuple[str, str]:
    """Return (private_key, public_key) by shelling out to the canonical
    `wg` binary: `wg genkey` then `wg pubkey`. Both are base64 X25519
    keys. Raises WireGuardError if `wg` is missing or errors.

    We don't re-implement Curve25519 in Python — the `wg` binary is the
    reference implementation, apt-installed by tasks/wireguard.yml, and
    matches what the kernel module expects byte-for-byte."""
    try:
        priv = subprocess.run(
            [wg_bin, "genkey"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except FileNotFoundError as exc:
        raise WireGuardError(
            f"`{wg_bin}` not found — install wireguard-tools "
            f"(`apt install wireguard-tools`)."
        ) from exc
    except subprocess.CalledProcessError as exc:
        raise WireGuardError(f"`wg genkey` failed: {exc.stderr.strip()}") from exc

    try:
        pub = subprocess.run(
            [wg_bin, "pubkey"],
            input=priv, check=True, capture_output=True, text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as exc:
        raise WireGuardError(f"`wg pubkey` failed: {exc.stderr.strip()}") from exc

    if not priv or not pub:
        raise WireGuardError("wg produced an empty key")
    return priv, pub


# ---------------------------------------------------------------------------
# IP allocation
# ---------------------------------------------------------------------------


def server_ip(subnet: str = DEFAULT_SUBNET) -> str:
    """The server interface IP — first usable host in the subnet
    (e.g. 10.99.0.1 for 10.99.0.0/24). Returned WITHOUT a prefix; the
    server conf appends the subnet prefix, client confs use /32."""
    net = _parse_subnet(subnet)
    # network_address is .0; first host is .1.
    return str(net.network_address + 1)


def allocate_client_ip(
    subnet: str,
    used_ips: Iterable[str],
) -> str:
    """Return the next-free client IP in `subnet` as a bare address
    string (no prefix). Sequential allocation starting at .2 (the
    server holds .1). `used_ips` is the set of already-assigned client
    IPs — bare addresses or CIDR (`10.99.0.5` or `10.99.0.5/32`), both
    accepted.

    Raises WireGuardError when the subnet is exhausted. A /24 holds
    ~253 clients (.2 through .254), which is well past the ~50-client
    per-node ceiling the design doc targets.
    """
    net = _parse_subnet(subnet)
    # Normalise used IPs to bare-address ints for fast membership.
    used: set[str] = set()
    for raw in used_ips:
        if not raw:
            continue
        addr = raw.split("/", 1)[0].strip()
        used.add(addr)

    server = str(net.network_address + 1)
    used.add(server)  # never hand out the server's own IP

    # Iterate hosts; .hosts() yields usable addresses (excludes network
    # + broadcast for IPv4). First candidate is .1 (server, already in
    # `used`), so the loop naturally starts handing out .2+.
    for host in net.hosts():
        cand = str(host)
        if cand not in used:
            return cand
    raise WireGuardError(
        f"WireGuard subnet {subnet} exhausted ({len(used)} addresses "
        f"in use). Widen the subnet via stealth_vps_wg_subnet."
    )


def _parse_subnet(subnet: str) -> ipaddress.IPv4Network:
    try:
        net = ipaddress.ip_network(subnet, strict=False)
    except ValueError as exc:
        raise WireGuardError(f"invalid WireGuard subnet {subnet!r}: {exc}") from exc
    if not isinstance(net, ipaddress.IPv4Network):
        raise WireGuardError(
            f"WireGuard subnet {subnet!r} must be IPv4 (v0.11.0 scope)"
        )
    if net.prefixlen > 30:
        raise WireGuardError(
            f"WireGuard subnet {subnet!r} too small (need /30 or wider for "
            f"at least one client)"
        )
    return net


# ---------------------------------------------------------------------------
# Config rendering
# ---------------------------------------------------------------------------


def render_server_conf(
    *,
    server_private_key: str,
    listen_port: int,
    subnet: str,
    peers: Iterable[tuple[str, str, str]],
) -> str:
    """Render /etc/wireguard/stealth.conf — the server interface +
    one [Peer] block per user.

    `peers` is an iterable of (label, client_pubkey, client_ip) tuples.
    `client_ip` may be bare or CIDR — we normalise to /32 in the
    AllowedIPs line (the server routes exactly that one client IP).

    Deterministic output: peers are sorted by label so repeated renders
    with the same input produce byte-identical files (matters for the
    `wg syncconf` no-op-on-unchanged path + git-diff review)."""
    net = _parse_subnet(subnet)
    server_addr = f"{net.network_address + 1}/{net.prefixlen}"

    lines = [
        "[Interface]",
        f"Address = {server_addr}",
        f"ListenPort = {int(listen_port)}",
        f"PrivateKey = {server_private_key}",
        "",
    ]
    for label, pubkey, client_ip in sorted(peers, key=lambda p: p[0]):
        bare_ip = client_ip.split("/", 1)[0].strip()
        lines.append(f"# {label}")
        lines.append("[Peer]")
        lines.append(f"PublicKey = {pubkey}")
        lines.append(f"AllowedIPs = {bare_ip}/32")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_client_conf(
    *,
    client_private_key: str,
    client_ip: str,
    server_public_key: str,
    endpoint_host: str,
    endpoint_port: int,
    dns: str = DEFAULT_CLIENT_DNS,
    allowed_ips: str = DEFAULT_CLIENT_ALLOWED_IPS,
    keepalive: int = DEFAULT_KEEPALIVE,
) -> str:
    """Render the per-user .conf the client imports into their WG app.

    `client_ip` may be bare or CIDR — normalised to /32 in the
    Interface Address line. `client_private_key` is the user's secret;
    on a server-gen flow the role hands this to the operator once and
    doesn't persist it in the index (only the pubkey lives there).

    The full-tunnel default (`allowed_ips=0.0.0.0/0, ::/0`) routes all
    client traffic through the VPN. Split-tunnel operators pass a
    narrower set."""
    bare_ip = client_ip.split("/", 1)[0].strip()
    lines = [
        "[Interface]",
        f"PrivateKey = {client_private_key}",
        f"Address = {bare_ip}/32",
        f"DNS = {dns}",
        "",
        "[Peer]",
        f"PublicKey = {server_public_key}",
        f"Endpoint = {endpoint_host}:{int(endpoint_port)}",
        f"AllowedIPs = {allowed_ips}",
        f"PersistentKeepalive = {int(keepalive)}",
    ]
    return "\n".join(lines) + "\n"
